# Base configs
baseurl: "https://oresttolovenko.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Orest Tokovenko"
subtitle: "See the world through my eyes!"
author: "Orest Tokovenko"
header:
 title: "Photography"
 subtitle: "by Orest Tokovenko"
footer:
 name: "Hey there, my name is Orest"
 bio: "I am a Developer and a Photographer from Canada"
 github: "Placeholder"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/le_simonaque"
 
